### ISSUE TITLE
Crash on Linux Mint 20.3 when selecting scenario due to UTF8 codec

### ISSUE THREAD

**Issue by anticitizn** [AuriTheGreat/McGovern#3]
```
pygame 2.1.2 (SDL 2.0.16, Python 3.8.10)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "Main.py", line 799, in <module>
    object.process()
  File "Main.py", line 144, in process
    self.onclickFunction(*self.paramsFunction)
  File "Main.py", line 395, in scenariomain
    gamedata=GameData(ScenarioHandler.main(scenarioname))
  File "/home/danny/devel/McGovern/McGovern/McGovern/ScenarioHandler.py", line 959, in main
    scenario.events=getevents(scenarioname)
  File "/home/danny/devel/McGovern/McGovern/McGovern/ScenarioHandler.py", line 808, in getevents
    l = np.array([ line.split() for line in f], dtype=object)
  File "/home/danny/devel/McGovern/McGovern/McGovern/ScenarioHandler.py", line 808, in <listcomp>
    l = np.array([ line.split() for line in f], dtype=object)
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa3 in position 515: invalid start byte
```

**Comment by anticitizn** [comment]
Also happens on Windows 10, even with 49272ecc1ea7f11adc23182c6568ca7eccc417de:
```
pygame 2.1.2 (SDL 2.0.18, Python 3.9.2)
Hello from the pygame community. https://www.pygame.org/contribute.html
["As defending world champions, England's venture in world cup", 'is attracting a much keener public interest than the general election.']
['Titanic has sunk']
['When Labour, led by Harold Wilson, took office in October 1964, it was immediately faced', 'with a deficit of 800 million pounds, which contributed to a series of sterling crises.', 'A possible solution was to devalue the pound against other currencies to make imports', 'more expensive (which meant more inflation), but exports cheaper, causing an increase.', '', 'By the summer of 1966, the pressure on sterling was acute but Wilson was determined to', "resist devaluation. To him the pound was a symbol of national status, of Britain's role", 'in the world as a key player. On 12 July 1966 the Cabinet rejected the devaluation option', 'and agreed to a tough package of deflation and austerity instead.']
worldcup  date>"1970-04-01" and date<"1970-09-02" and labour.leader==wilson [<ScenarioHandler.getevents.<locals>.Event object at 0x0000026E3B852850>]
titanic  date>"1966-04-01" and date<"1970-09-02" and labour.leader==wilson [<ScenarioHandler.getevents.<locals>.Event object at 0x0000026E3D0204C0>]
devaluation  date>"1967-11-16" [<ScenarioHandler.getevents.<locals>.Event object at 0x0000026E3B852910>]
Traceback (most recent call last):
  File "C:\Users\neykoda\source\repos\McGovern\McGovern\McGovern\Main.py", line 799, in <module>
    object.process()
  File "C:\Users\neykoda\source\repos\McGovern\McGovern\McGovern\Main.py", line 144, in process
    self.onclickFunction(*self.paramsFunction)
  File "C:\Users\neykoda\source\repos\McGovern\McGovern\McGovern\Main.py", line 398, in scenariomain
    gamedata.results=ResultHandler.getresults(gamedata.scenario)
  File "C:\Users\neykoda\source\repos\McGovern\McGovern\McGovern\ResultHandler.py", line 243, in getresults
    results.printresults()
  File "C:\Users\neykoda\source\repos\McGovern\McGovern\McGovern\ResultHandler.py", line 22, in printresults
    print("+" + "".join([chr(0x2015) for c in range(95)]) + "+")
  File "C:\Users\neykoda\AppData\Local\Programs\Python\Python39\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode characters in position 1-95: character maps to <undefined>
```
